Adding 'Atlas toolkit' as new tool.
thibmaek/awesome-raspberry-pi pull request #170
Opened 2020-09-09 16:14 UTC by epeios-q37

# Please make sure all below checkboxes have been checked before submitting your PR.

- [ ] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [ ] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- The topic I added
  - [ ] includes a valid (https) link,
  - [ ] includes a concise and on-topic description,
  - [ ] mentions if there is only support some devices,
  - [ ] is not a duplicate,
  - [ ] has been in the correct alphabetical order for its section,
  - [ ] is in the form of **Named Link - Description, seperated by commas.**
  - [ ] ends with a dot.

2020-09-10 08:29 UTC, thibmaek requested changes

2020-09-10 08:29 UTC, thibmaek commented on README.md
> +- [*Atlas* toolkit](https://github.com/epeios-q37/atlas-python) - Very lightweight and easy to install toolkit to write in *Python* (no *JavaScript* needed) web applications to pilot your RPi, withou
Couple of remarks:

- Don't use markup inside of the link or description.
- Skip the Javascript part, that's irrelevant to the short summary

2020-09-10 12:25 UTC, epeios-q37 commented on README.md
> +- [*Atlas* toolkit](https://github.com/epeios-q37/atlas-python) - Very lightweight and easy to install toolkit to write in *Python* (no *JavaScript* needed) web applications to pilot your RPi, withou
The JS part was so the reader does not think that the Atlas toolkit is yet another framework to produce single-page application where the backend is written in Python, but the frontend in JS… (the Atlas toolkit is not for writing CGI-like application either).

2020-09-10 12:31 UTC, thibmaek commented
🤝 Thanks for contributing this resource!

2020-09-10 12:32 UTC, merged

2020-09-11 01:16 UTC, JZavalaa commented
I'll pass on this.   
  
  
  

  
  

  
  
>   
> On Sep 10, 2020 at 7:26 AM,  <Claude SIMON (mailto:notifications@github.com)>  wrote:
>   
>   
>   
>
>
>
>   
>
> @epeios-q37  commented on this pull request.
>
>     
>
> In   README.md (https://github.com/thibmaek/awesome-raspberry-pi/pull/170#discussion_r486293910):
>
>   
>   >  @@ -94,6 +94,7 @@ The complete collection of (consumer) Raspberry Pi models consist of: - [Alpha](https://github.com/farjump/raspberry-pi) - Remotely load, debug and test bare-metal programs using GDB with this system-level GDB server. - [ApplePi Bakery](http://www.tweaking4all.com/software/macosx-software/macosx-apple-pi-baker/) - macOS application to easily install/backup/restore images onto an SD card. +- [*Atlas* toolkit](https://github.com/epeios-q37/atlas-python) - Very lightweight and easy to install toolkit to write in *Python* (no *JavaScript* needed) web applications to pilot your RPi, without having to install a web server.  
>   
>
> The JS part was so the reader does not think that the Atlas toolkit is yet another framework to produce single-page application where the backend is written in Python, but the frontend in JS… (the Atlas toolkit is not for writing CGI-like application either).
>
>   
>
> —
>  You are receiving this because you are subscribed to this thread.
>  Reply to this email directly,   view it on GitHub (https://github.com/thibmaek/awesome-raspberry-pi/pull/170#discussion_r486293910), or   unsubscribe (https://github.com/notifications/unsubscribe-auth/ALKPIPMOIJWODJN2GIFW2PTSFDAWXANCNFSM4RCVDKYA).
>
>   
>

2020-09-11 10:03 UTC, thibmaek commented
> I'll pass on this.

@JZavalaa i am not sure what you mean? I don't think this PR relates to you in any way?