Add drumbooth project + @FDelporte as a contributor
thibmaek/awesome-raspberry-pi pull request #172
Opened 2020-09-15 15:20 UTC by FDelporte

# Please make sure all below checkboxes have been checked before submitting your PR.

- [ ] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [ ] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- The topic I added
  - [ ] includes a valid (https) link,
  - [ ] includes a concise and on-topic description,
  - [ ] mentions if there is only support some devices,
  - [ ] is not a duplicate,
  - [ ] has been in the correct alphabetical order for its section,
  - [ ] is in the form of **Named Link - Description, seperated by commas.**
  - [ ] ends with a dot.

2020-09-15 15:29 UTC, thibmaek requested changes

2020-09-15 15:29 UTC, thibmaek commented on .all-contributorsrc
> +      "contributions": [
These are not valid contributions. Please specify `doc` instead of the invalid ones here

2020-09-15 20:06 UTC, FDelporte commented on .all-contributorsrc
> +      "contributions": [
removed this change, will do in different PR

2020-09-17 09:16 UTC, thibmaek approved these changes

2020-09-17 09:16 UTC, merged