Added book "Getting Started with Java on the Raspberry Pi"
thibmaek/awesome-raspberry-pi pull request #173
Opened 2020-09-15 15:21 UTC by FDelporte

# Please make sure all below checkboxes have been checked before submitting your PR.

- [ ] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [ ] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- The topic I added
  - [ ] includes a valid (https) link,
  - [ ] includes a concise and on-topic description,
  - [ ] mentions if there is only support some devices,
  - [ ] is not a duplicate,
  - [ ] has been in the correct alphabetical order for its section,
  - [ ] is in the form of **Named Link - Description, seperated by commas.**
  - [ ] ends with a dot.

2020-09-15 15:27 UTC, thibmaek requested changes

2020-09-15 15:27 UTC, thibmaek commented on README.md
> +- [Getting Started with Java on the Raspberry Pi (published 2020)](https://webtechie.be/books/) - A lot of info and history about Java itself and how to install and use it on the Raspberry Pi with a
Omit the `(published 2020)` part please

2020-09-15 15:27 UTC, thibmaek commented on README.md
> +- [Getting Started with Java on the Raspberry Pi (published 2020)](https://webtechie.be/books/) - A lot of info and history about Java itself and how to install and use it on the Raspberry Pi with a
```suggestion
- [Getting Started with Java on the Raspberry Pi](https://leanpub.com/gettingstartedwithjavaontheraspberrypi) - Book on how to install & use Java with a lot of example projects.
```

2020-09-15 15:27 UTC, thibmaek commented on README.md
> +- [Getting Started with Java on the Raspberry Pi (published 2020)](https://webtechie.be/books/) - A lot of info and history about Java itself and how to install and use it on the Raspberry Pi with a
I would link to Leanpub instead of a generic /books page

2020-09-15 20:00 UTC, FDelporte commented on README.md
> +- [Getting Started with Java on the Raspberry Pi (published 2020)](https://webtechie.be/books/) - A lot of info and history about Java itself and how to install and use it on the Raspberry Pi with a
thanks for your feedback! both remarks done

2020-09-17 09:15 UTC, thibmaek approved these changes
🤝 Thanks for contributing this resource!

2020-09-17 09:15 UTC, merged

2020-09-17 09:18 UTC, FDelporte commented
@thibmaek thanks for sharing!!!