Added raspcontroller and teamviewer to apps section
thibmaek/awesome-raspberry-pi pull request #187
Opened 2020-10-03 08:58 UTC by AnnleeFores

# Please make sure all below checkboxes have been checked before submitting your PR.

- [ ] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [ ] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- The topic I added
  - [ ] includes a valid (https) link,
  - [ ] includes a concise and on-topic description,
  - [ ] mentions if there is only support some devices,
  - [ ] is not a duplicate,
  - [ ] has been in the correct alphabetical order for its section,
  - [ ] is in the form of **Named Link - Description, seperated by commas.**
  - [ ] ends with a dot.

2020-10-03 17:12 UTC, thibmaek requested changes

2020-10-03 17:12 UTC, thibmaek commented on README.md
> +- **RaspController** - Manage your Raspberry Pi remotely, control the GPIO ports, send commands directly through the terminal, view images from a connected camera and obtain data from different senso
Should be placed above Raspicast

2020-10-03 19:41 UTC, AnnleeFores commented on README.md
> +- **RaspController** - Manage your Raspberry Pi remotely, control the GPIO ports, send commands directly through the terminal, view images from a connected camera and obtain data from different senso
my bad 😅

2020-10-05 12:34 UTC, thibmaek approved these changes

2020-10-05 12:34 UTC, merged