Added PiGro to README.md
thibmaek/awesome-raspberry-pi pull request #250
Opened 2024-01-22 18:43 UTC by actionschnitzel

# Please make sure all below checkboxes have been checked before submitting your PR.

- [x] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [x] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- The topic I added
  - [x] includes a valid (https) link,
  - [x] includes a concise and on-topic description,
  - [x] mentions if there is only support some devices,
  - [x] is not a duplicate,
  - [x] has been in the correct alphabetical order for its section,
  - [x] is in the form of **Named Link - Description, separated by commas.**
  - [x] ends with a dot.

2024-01-22 20:45 UTC, thibmaek requested changes

2024-01-22 20:45 UTC, thibmaek commented on README.md
> +- [PiGro - Just Click It!](https://github.com/actionschnitzel/PiGro-Aid-) - Everything you need to use the Pi as a desktop computer. PiGro does many commands that have to be entered via the terminal
Description itself needs to be one sentence

2024-01-22 20:46 UTC, thibmaek commented
Hi! Thanks for the contribution, can you double check the contribution guidelines, the PR checklist and the remarks on this PR in order to complete it?

2024-01-22 22:20 UTC, actionschnitzel reviewed
Application name and description shortened.
The full name is "PiGro - Just Click It!"

2024-01-23 08:17 UTC, thibmaek approved these changes

2024-01-23 08:17 UTC, thibmaek commented
🤝 Thanks for contributing this resource!

2024-01-23 08:17 UTC, merged